fonytask_index:
   path: /tasks
   controller: App\Controller\TaskController::index

user_registration:
   path: /user/registration
   controller: App\Controller\UserController::register

login:
   path: /
   controller: App\Controller\UserController::login

logout:
   path: /logout

task_detail:
   path: /task/detail/{id}
   controller: App\Controller\TaskController::detail

task_create:
   path: /task/create
   controller: App\Controller\TaskController::create

task_edit:
   path: /task/edit/{id}
   controller: App\Controller\TaskController::edit

task_deletion:
   path: /task/deletion/{id}
   controller: App\Controller\TaskController::delete

my_task:
   path: /my-tasks
   controller: App\Controller\TaskController::myTasks
